pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/alex01shappard/Labs_for_MLops.git', branch: 'main'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'python -m pip install --upgrade pip'
                sh 'pip install -r lab2/requirements.txt'
            }
        }
        
        stage('Data Processing') {
            steps {
                sh 'python lab2/scripts/data_processing.py'
            }
        }
        
        stage('Model Training') {
            steps {
                sh 'python lab2/scripts/model_training.py'
            }
        }
        
        stage('Model Testing') {
            steps {
                sh 'python lab2/scripts/model_testing.py'
            }
        }
    }
}